version: 1.0.2.{build}
image: Visual Studio 2017
assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test:
  assemblies:
    only:
      - '**\*.UnitTests.dll'